name: Ping Koyeb health

on:
  schedule:
    - cron: "*/10 * * * *" # mỗi 10 phút
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          curl -fsS "https://banlabacsicuachinhminh.koyeb.app/api/health" >/dev/null
